#!/usr/bin/python



want_attrs = [
    'DaemonStartTime',
    'CPUsUsage',
    'Cpus',
    'MemoryUsage',  # max observed
    'GLIDEIN_Site',
    'GLIDEIN_ResourceName',
    'Machine',
]

schema_sql = """
create table data
( tstamp
, %s
);
""" % "\n, ".join(want_attrs)

filter_cond = 'true'

def query_current_attrs(ad):
    """ ad is for collector """
    import htcondor
    import classad
    pool = 'flock.opensciencegrid.org' #:9618
    name = 'yyy'
    dbpath = 'data.db'
    coll = htcondor.Collector(pool)
    colld = coll.locate(htcondor.DaemonTypes.Collector, name)
    db_exists = os.path.exists(dbpath)
    sqldb = sqlite3.connect(dbpath)
    if not db_exists:
        sqldb.execute(schema_sql)

    qmarks = ",".join(["?"]*len(want_attrs))
    insert_sql = "insert into data values (%s)" % qmarks

    current_ts = time.now()
    for job in colld.xquery(filter_cond, want_attrs):
        vals = list(map(job.get, want_attrs))
        sqldb.execute(insert_sql, vals)





